# Site settings
title: Kaushik Kanetkar - blog
email: kaushik.kanetkar@gmail.com
description: "Let the machines learn"
baseurl: ""
url: "http://kaushikkanetkar.github.io"
github_username:  kaushikkanetkar

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
